services:
  bot:
    build: .
    environment:
      - MONGO_URI=mongodb://db:27017/
      - BOT_TOKEN=${BOT_TOKEN:?BOT_TOKEN must be set}
    depends_on:
      - db
    networks:
      - open-web-net
      - internal-net

  db:
    image: mongo:8.0.4
    networks:
      - internal-net
    volumes:
      - mongo-data:/data/db

networks:
  open-web-net:
    driver: bridge
  internal-net:
    driver: bridge
    internal: true

volumes:
  mongo-data:
